### ISSUE TITLE
Menu bar transform while trying to scroll inside

### ISSUE THREAD

**Issue by peterujah** [ericktatsui/Touch-Menu-Like-Android#10]
I just like this library, it exactly what I have been looking for my webview app. But the problem is that when I scroll, the menu transforms so the point is, i can't scroll up or down, I have also checked the demo link http://ericktatsui.github.io/Touch-Menu-Like-Android/sample.html, and is also the same thing. Please is there any fix for this? I have tried removing this `panstart`, it doesn't fix the issue

**Comment by ericktatsui** [comment]
Hi @peterujah, this library is deprecated and I do not recomend you to keep using it, I haven't updated it since january 2017.
