### ISSUE TITLE
Add a Drop Down

### ISSUE THREAD

**Issue by gxcplcto** [ericktatsui/Touch-Menu-Like-Android#4]
Can there be a dropdown menu added to the menu. Say for example if there are sub-menus in a particular menu, then how can they have the effect of displaying the sub-menu when the main menu item is clicked?

Any help would be appreciated.

Regards!

**Comment by ericktatsui** [comment]
Hello.
The objective of this library is only offer the touch slide behaivor like the android drawer navigation.
This library is totaly compatible with other, so you can use other library inside the drawer to complement.
