### ISSUE TITLE
It's buggy if you want to scroll the menu

### ISSUE THREAD

**Issue by ghost** [ericktatsui/Touch-Menu-Like-Android#9]
If you scroll the menu, the menu jumps directly somewhere

**Comment by bridge2web** [comment]
https://github.com/ericktatsui/Touch-Menu-Like-Android/issues/3#issuecomment-277232000

@Dimosthenis comment
> I fixed it by removing "panstart" event in line 62:
> TouchMenuLA.prototype.touchStartMenu = function () { menuHammer.on('panstart panmove', function (ev) { ...

Additionally, I fix mask
`.tmla-mask {
        position: fixed !important;
    }`
